draw_set_color(c_white)
draw_set_alpha(0.5)
draw_rectangle_color(0,0,1024,768,c_black,c_black,c_black,c_black,false)
draw_set_alpha(1)
draw_set_font(global.deathfont)
draw_text(16,700,"Subscribed Workshop Challenges")
