image_blend = c_white
anim += 0.5 * (60 / global.maxfps)
switch(global.skinselected) {
default: sprite_index = s_playerred break;
case(1): sprite_index = s_kaizoplayerred break;
case(2): sprite_index = s_madplayerred break;
case(3): sprite_index = s_blindplayerred break;
case(4): sprite_index = s_sadplayerredIDLE break;
case(5): sprite_index = s_blockplayerred break;
case(6): sprite_index = s_hdplayerred break;
case(7): sprite_index = s_rewardedplayerred break;
case(8): sprite_index = s_angryplayerred break;
case(9): sprite_index = s_coolplayerred break;
case(10): sprite_index = s_thedarkknightskin break;
case(11): sprite_index = s_richplayerred break;
case(12): sprite_index = s_goldplayerskin break;
case(13): sprite_index = s_frozenplayerred break;
case(14): image_blend = make_color_rgb(255,0,0)
sprite_index = s_kindadeadplayerskin
break;
case(15): sprite_index = s_coronaplayerred break;
case(16): sprite_index = s_canadianplayerred break;
case(17): sprite_index = s_hazardousplayerskinmenuthingy break;
case(18): sprite_index = s_babyplayerred break;
case(19): sprite_index = s_hexagonplayerred break;
case(20): sprite_index = s_tuxedoplayerred break;
case(22): sprite_index = s_waterplayerred break;
case(23): image_blend = make_color_rgb(255,0,0)
sprite_index = s_forseneplayerskin
break;
case(24): sprite_index = s_redballplayerskinmenu break;
case(25): sprite_index = s_bomberplayerskin break;
case(26): image_blend = make_color_rgb(255,0,0)
sprite_index = s_hitboxplayerskin break;
case(27): image_blend = make_color_rgb(255,0,0)
sprite_index = s_metallicplayerskin break;
case(28): sprite_index = s_monocleplayerskin break;
case(29): image_blend = make_color_rgb(255,0,0)
sprite_index = s_japaneseplayerskin break;
case(30): sprite_index = s_googlyeyeskin break;
case(31): image_blend = make_color_rgb(255,0,0)
sprite_index = s_upsidedownplayerskin break;
case(32): sprite_index = s_spiralplayerskin break;
case(33): sprite_index = s_heartplayerskin break;
case(34): image_blend = make_color_rgb(255,0,0) break;
case(36): image_blend = make_color_rgb(255,0,0)
sprite_index = s_arrowplayerskin break;
case(37): image_blend = make_color_rgb(255,0,0)
sprite_index = s_spikeplayerskin break;
case(38): image_blend = make_color_rgb(255,0,0)
sprite_index = s_splitplayerskin break;
case(39): sprite_index = s_pirateplayerskin break;
case(41): sprite_index = s_gordonplayerskin break;
case(42): sprite_index = s_fancyplayerskin break;
case(43): image_blend = make_color_rgb(255,0,0)
sprite_index = s_steamplayerskin break;
case(44): image_blend = make_color_rgb(255,0,0)
sprite_index = s_breakableplayerskin break;
case(45): image_blend = make_color_rgb(255,0,0)
sprite_index = s_smileyplayerskin break;
case(49): sprite_index = s_kratosplayerskin break;
break;
}