#macro TUTORIALCHALLENGETIME "CgkI36PRjvEQEAIQLg"
#macro LADDERCHALLENGETIME "CgkI36PRjvEQEAIQLw"
#macro INVISIBLECHALLENGETIME "CgkI36PRjvEQEAIQMA"
#macro DAILYLEVELSTREAKLEADERBOARD "CgkI36PRjvEQEAIQMQ"
