draw_set_alpha(0.5) draw_set_color(c_black) draw_rectangle(x+75,y-10,room_width-75,room_height-100,false)
draw_set_alpha(1)
draw_set_color(c_yellow) draw_text(x+85,y,"Developer: ")
draw_set_color(c_white) draw_text(x+85+string_width("Developer: "),y,"Infiland")
draw_set_color(c_yellow) draw_text(x+85,y+20,"Level Layouts and Ideas: ")
draw_set_color(c_white) draw_text(x+85+string_width("Level Layouts and Ideas: "),y+20,"Infiland, my friends & family, and the awesome TCC Community!")
draw_set_color(c_yellow) draw_text(x+85,y+40,"Art and Sprites: ")
draw_set_color(c_white) draw_text(x+85+string_width("Art and Sprites: "),y+40,"Infiland, Lomany, sundisc_")
draw_set_color(c_yellow) draw_text(x+85,y+60,"Music: ")
draw_set_color(c_white) draw_text(x+85+string_width("Music: "),y+60,"Infiland, 3kliksphilip, Loeder, LHSSchiptunes, Sam Beddoes, Kevin Mecleod, MK2")
draw_set_color(c_yellow) draw_text(x+85,y+80,"Most of the Code by: ")
draw_set_color(c_white) draw_text(x+85+string_width("Most of the Code by: "),y+80,"Infiland")
draw_set_color(c_yellow) draw_text(x+85,y+100,"Secondary Code Helpers: ")
draw_set_color(c_white) draw_text(x+85+string_width("Secondary Code Helpers: "),y+100,"Shaun Spalding, Heartbeast and the GMS2 Community!")
draw_set_color(c_yellow) draw_text(x+85,y+120,"Linux Support: ")
draw_set_color(c_white) draw_text(x+85+string_width("Linux Support: "),y+120,"Monou")
draw_set_color(c_yellow) draw_text(x+85,y+140,"Beta Playtesting: ")
draw_set_color(c_white) draw_text(x+85+string_width("Beta Playtesting: "),y+140,"Nightmareyoc, KoiQu, HaLL, BLaacK, Sapero, Sydew, dha, Monst2r,\nMonou, YoExploshi, TheDarkBomber, friends and family!")
draw_set_color(c_yellow) draw_text(x+85,y+180,"German Translation: ")
draw_set_color(c_white) draw_text(x+85+string_width("German Translation: "),y+180,"BLaacK, devc, KD10, Reisch")
draw_set_color(c_yellow) draw_text(x+85,y+200,"French Translation: ")
draw_set_color(c_white) draw_text(x+85+string_width("French Translation: "),y+200,"Maghreb, Sanslesquellete")
draw_set_color(c_yellow) draw_text(x+85,y+220,"Italian Translation: ")
draw_set_color(c_white) draw_text(x+85+string_width("Italian Translation: "),y+220,"dha, Thristy Boi")
draw_set_color(c_yellow) draw_text(x+85,y+240,"Spanish Translation: ")
draw_set_color(c_white) draw_text(x+85+string_width("Spanish Translation: "),y+240,"SuperYoshi_13")
draw_set_color(c_yellow) draw_text(x+85,y+260,"Chinese Translation: ")
draw_set_color(c_white) draw_text(x+85+string_width("Chinese Translation: "),y+260,"TaipeiNative")