draw_set_font(fnt_cool2)
draw_set_alpha(0.5) draw_set_color(c_black) draw_rectangle(x+75,y-110,room_width-75,room_height-100,false)
draw_set_alpha(1)
draw_set_color(c_yellow) draw_text(x+85,y,"Developer: ")
draw_set_color(c_white) draw_text(x+85+string_width("Developer: "),y,"Infiland")
draw_set_color(c_yellow) draw_text(x+85,y+20,"Level Layouts and Ideas: ")
draw_set_color(c_white) draw_text(x+85+string_width("Level Layouts and Ideas: "),y+20,"Infiland, my friends & family, and the awesome TCC Community!")
draw_set_color(c_yellow) draw_text(x+85,y+40,"Art and Sprites: ")
draw_set_color(c_white) draw_text(x+85+string_width("Art and Sprites: "),y+40,"Infiland, Lomany, sundisc_, Kenney")
draw_set_color(c_yellow) draw_text(x+85,y+60,"Music: ")
draw_set_color(c_white) draw_text(x+85+string_width("Music: "),y+60,"Infiland, 3kliksphilip, PVCFaust, Sam Beddoes, Kevin Mecleod, MK2")
draw_set_color(c_yellow) draw_text(x+85,y+80,"Most of the Code by: ")
draw_set_color(c_white) draw_text(x+85+string_width("Most of the Code by: "),y+80,"Infiland")
draw_set_color(c_yellow) draw_text(x+85,y+100,"Secondary Helpers: ")
draw_set_color(c_white) draw_text(x+85+string_width("Secondary Helpers: "),y+100,"Shaun Spalding, Heartbeast, jujuadams and the GMS2 Community!")
draw_set_color(c_yellow) draw_text(x+85,y+120,"Linux Support: ")
draw_set_color(c_white) draw_text(x+85+string_width("Linux Support: "),y+120,"Monou")
draw_set_color(c_yellow) draw_text(x+85,y+140,"Beta Playtesting: ")
draw_set_color(c_white) draw_text(x+85+string_width("Beta Playtesting: "),y+140,"Nightmareyoc, KoiQu, HaLL, BLaacK, Sapero, Sydew, dha, bobinsky,\nMonou, YoExploshi, TheDarkBomber, MasterX, Jodza\nfriends and family!")

draw_set_color(c_white) draw_text(x+545,y+445,"Click the 'RETURN' button to go back.")